### ISSUE TITLE
What does spatial_feature_extract do?

### ISSUE THREAD

**Issue by moonmoonCL** [futscdav/strotss#3]
Hi，
Thanks for sharing your work！
I'm trying to understand the code， 
and could you tell me what does spatial_feature_extract do?
Thanks！

**Comment by futscdav** [comment]
In short, it extracts the feature hypercolumns at given x and y locations, with bilinear interpolation for smaller scales of features maps. You could do it by upscaling the small feature maps, but that is about 3x slower than doing it like this.
