### ISSUE TITLE
any way to use a seed for the random values?

### ISSUE THREAD

**Issue by edstoica** [futscdav/strotss#6]
i am wondering if it may be possible to get "repeatable" outputs, when locking all random stuff in the code to a seed?
or is it in strotss' nature to be random?

btw: I love this repo so much. its handy to use and easy to install... brilliant. thank you again!
Currently I am doing experiments with 1k resolution and 1000 iterations... yes takes some time, but the results are just so stunning...

**Comment by futscdav** [comment]
You can get somewhat close to reproducible results by calling 
```
torch.manual_seed(0)
np.random.seed(0)
```
before the `strotss` function is called.

Sadly, fully reproducible results are not possible with current PyTorch implementations on GPU. You can achieve it on CPU (pass --device cpu) by also adding `torch.use_deterministic_algorithms(True)`, but it will obviously run orders of magnitude slower on CPU (e.g. on my machine the demo 512x503 runs in 45s on GPU but 15 min on CPU).

**Comment by edstoica** [comment]
thank you for that.
I will evaluate this later in my next experients... :)

just tried to use my cpu, and can report, that works well on ryzen cores.
1024x1024 with 200 iterations took 3200 seconds compared to 90s on rtx3080.
